name: CI

on: [push, pull_request]

env:
  DATABASE_URL: 'https://fake.com'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deps
        run: npm install

      - name: Types
        run: npm run types

      - name: Lint
        run: npm run lint
